ISSUE-138 - Fixed to show autor and category on the listing page
ChristopherDosin/Shopware-6-Blog-Plugin pull request #142
Opened 2023-01-13 04:35 UTC by hungmac-sw

2023-01-13 06:47 UTC, ChristopherDosin requested changes

2023-01-13 06:47 UTC, ChristopherDosin commented on CHANGELOG_de-DE.md
> +* Das Hinzufügen von BlogSubscriber zu services.xml wurde korrigiert, jetzt können wir auf der Auflistungsseite nach Autor und Kategorie filtern
Fixed BlogSubscriber um nach Autoren & Kategorien um Listing zu suchen

2023-01-13 06:47 UTC, ChristopherDosin commented on CHANGELOG_de-DE.md
> +* Fixed to show the author and category in the blog
Problem behoben, dass den Autor & Kategorie nicht im Blog Beitrag anzeigt.

2023-01-13 06:47 UTC, ChristopherDosin commented on CHANGELOG_en-GB.md
> +* Fixed to show the author and category in the blog
Fix to show the author and category within the blog detail page.

2023-01-13 06:49 UTC, ChristopherDosin commented
@hungmac-sw Can we add this as a 1.5.12 release? Because this bug is crucial i guess.

2023-01-13 10:42 UTC, hungmac-sw commented
@ChristopherDosin I will release it in version 1.5.12 in a new PR for the release

2023-01-13 11:04 UTC, ChristopherDosin commented on .github/workflows/pr.yml
> +        shopware: [ '6.4.18.0' ]
What is the reason we're only checking for `6.4.18.0` ?

2023-01-13 17:23 UTC, hungmac-sw commented on .github/workflows/pr.yml
> +        shopware: [ '6.4.18.0' ]
with the PR we check only the latest version, with the release we will check all of the versions.
Check all of the support versions on the PR, I think it will take about 15 minutes for each PR update/delete instead of it, I will test on v6.4.18 and [v6.4.6](https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/142/files#diff-15c806aa509538190832852f439e9921a23bec2da81f95ed0e4bf13c14e5b160R104) here

2023-01-14 07:56 UTC, ChristopherDosin commented on .github/workflows/pr.yml
> +        shopware: [ '6.4.18.0' ]
ok

2023-01-14 07:57 UTC, ChristopherDosin approved these changes

2023-01-14 07:57 UTC, merged

2023-02-07 16:12 UTC, TimWuyts commented
Release seems to be still not available on store.shopware.com. Version remains 1.5.11.

2023-02-08 04:25 UTC, hungmac-sw commented
@ChristopherDosin please merge this PR https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/150 to fix the automatic release

2023-02-08 04:38 UTC, ChristopherDosin commented
@hungmac-sw Done, thanks for the hint.

2023-02-08 05:25 UTC, hungmac-sw commented
@ChristopherDosin Anyway, to release the 1.5.12 version to the store you have to do it manually now because I don't have permission to re-run the release. The zip file is already here https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/releases/tag/1.5.12